sudo: false
language: python
python:
- '2.7'
- '3.4'
- '3.5'
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - python-opencv
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib
  h5py pillow scikit-image pandas six
- source activate test-environment
- pip install pytest pytest-benchmark pytest-cov pytest-xdist pytest-flakes
- pip install coveralls iso8601
- CC=/usr/bin/gcc-4.9 CXX=/usr/bin/g++-4.9 pip install pycapnp
- pip install -e .
script:
- cd python && py.test
after_success:
- coveralls
notifications:
  slack:
    secure: nifpcO1W7JQ2Fk31qxGAnbzFg1B4wzq7AaLGSKn3BAIXgvAo6UuzyD5HgvG57tJNTaiMtVz3JGZx213cmq0WjY7ZD7VI7QL3NGYSX75EEWYXaatzGQa1uUucyfzZznRa/lKyamPbN//Xl5+Y38yrTZstCkszN2FovsOssW6Ymyk3bonIusGWB+JyjDD3Qn4aR3H6K7K/gX8BoyV31ec3Cs93/U87cHRw5kNfgqCYl+fcWxajN2YGaCFtuZJdjsYvNqz4pzsmAmxET7DBsxxQRnJGCCJhJLRDEhlcN0oSdQnTQCelmxECSDPJr4W6lVY6YxuQnkUTpFrjs0FcPBR7HSoauOWCo9apCaX8z+D6mMGMfUKZsOl0Qcyi1nqQ3ZN0FNLCM0+VXABRc5z6M0kIVeG0oi4bvUANHqG9xDcXK2QYomycsfDXZNIwohwZOqLumgQLwaDF1LpseR0AYRbfzLszTWHckYXM9EqwzG2TI5+BqFwJ6QOrJJM0AUAYs9gdv/zFgsNEs/ozBiaHypSEne5CvfxowKDZRGIZLr+BMWi8V/aRJYGFtxpovNSXARYw06XyyCIps4RHjrtCwdev5MJkjGZlH/8m/5ZI2Z67IDej7K6WXQQ2B8N5WWyhWL5QrZhnN+1wHC6RiGcRhxX9erM+ZS3r4h/feh0+9fXzGE0=
